[server]
headless = true
enableStaticServing = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF9600"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#3C3C3C"
font = "sans serif"
